"""unverified emails

Revision ID: 508ea801e1c0
Revises: db871b5702c8
Create Date: 2018-12-01 21:14:41.211170

"""

# revision identifiers, used by Alembic.
revision = '508ea801e1c0'
down_revision = 'db871b5702c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE emails SET verified = TRUE")


def downgrade():
    op.execute("DELETE FROM emails WHERE verified = FALSE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'verified')
    # ### end Alembic commands ###
