"""routing_rules.

Revision ID: c5b223503d70
Revises: ddfbedf24998
Create Date: 2019-02-08 09:36:21.285025

"""

# revision identifiers, used by Alembic.
revision = "c5b223503d70"
down_revision = "ddfbedf24998"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("trigger", postgresql.JSON(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("routing_rules")
    # ### end Alembic commands ###
