"""add submission spam field

Revision ID: fc9a8d5b9ad4
Revises: 0d62aefafa13
Create Date: 2019-01-16 14:40:23.276935

"""

# revision identifiers, used by Alembic.
revision = 'fc9a8d5b9ad4'
down_revision = '0d62aefafa13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('spam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'spam')
    # ### end Alembic commands ###
